# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://travis-ci.org/
language: node_js
node_js:
  - "6"
  - "8"
before_install:
  - sudo apt-get install google-chrome-stable
install:
  - npm install
script:
  - npm run build
branches:
  only:
    - master